=== ai4ci/jpansim2/src/test/resources/schema.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "definitions" : {
    "ImmutableEmpiricalFunction" : {
      "type" : "object",
      "properties" : {
        "link" : {
          "type" : "string",
          "enum" : [ "NONE", "LOG", "LOGIT" ]
        },
        "x" : {
          "type" : "array",
          "items" : {
            "type" : "number"
          }
        },
        "y" : {
          "type" : "array",
          "items" : {
            "type" : "number"
          }
        }
      }
    },
    "ImmutableFixedValueFunction" : {
      "type" : "object",
      "properties" : {
        "value" : {
          "type" : "number"
        }
      }
    },
    "ImmutablePhenomenologicalModel" : {
      "type" : "object",
      "properties" : {
        "approxPeakImmuneResponse" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "approxPeakViralLoad" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "immuneWaningHalfLife" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "incubationPeriod" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "incubationToPeakViralLoadDelay" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "infectiousnessCutoff" : {
          "type" : "number"
        },
        "peakImmuneResponseDelay" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "peakToRecoveryDelay" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        }
      }
    },
    "ImmutableSimpleDistribution" : {
      "type" : "object",
      "properties" : {
        "central" : {
          "type" : "number"
        },
        "dispersion" : {
          "type" : "number"
        },
        "type" : {
          "type" : "string",
          "enum" : [ "BINOM", "POIS", "NEG_BINOM", "GAMMA", "NORM", "LOG_NORM", "LOGIT_NORM", "UNIMODAL_BETA", "BETA", "POINT", "UNIFORM0", "RESAMPLE" ]
        }
      }
    },
    "ImmutableStochasticModel" : {
      "type" : "object",
      "properties" : {
        "baselineViralInfectionRate" : {
          "type" : "number"
        },
        "baselineViralReplicationRate" : {
          "type" : "number"
        },
        "immuneActivationRate" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "immuneTargetRatio" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "immuneWaningRate" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "infectionCarrierProbability" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "targetCellCount" : {
          "type" : "integer"
        },
        "targetRecoveryRate" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "virionsDiseaseCutoff" : {
          "type" : "integer"
        }
      }
    },
    "TestParameters" : {
      "type" : "object"
    }
  },
  "type" : "object",
  "properties" : {
    "batchConfig" : {
      "type" : "object",
      "properties" : {
        "exporters" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "enum" : [ "SUMMARY", "INTERNAL_STATE", "HISTORICAL_TESTS", "CONTACT_NETWORK", "INFECTIVITY_PROFILE", "DEMOGRAPHICS" ]
          }
        },
        "simulationDuration" : {
          "type" : "integer"
        },
        "urnBase" : {
          "type" : "string"
        }
      }
    },
    "executionConfig" : {
      "type" : "object",
      "properties" : {
        "appUseProbability" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "asymptomaticFraction" : {
          "type" : "number"
        },
        "availableTests" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/TestParameters"
          }
        },
        "caseFatalityRate" : {
          "type" : "number"
        },
        "caseHospitalisationRate" : {
          "type" : "number"
        },
        "complianceProbability" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "contactDetectedProbability" : {
          "type" : "number"
        },
        "contactProbability" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "defaultBehaviourModelName" : {
          "type" : "string"
        },
        "defaultPolicyModelName" : {
          "type" : "string"
        },
        "importationProbability" : {
          "type" : "number"
        },
        "inHostConfiguration" : {
          "anyOf" : [ {
            "$ref" : "#/definitions/ImmutableStochasticModel"
          }, {
            "$ref" : "#/definitions/ImmutablePhenomenologicalModel"
          } ]
        },
        "initialEstimateInfectionDuration" : {
          "type" : "number"
        },
        "initialEstimateSymptomSensitivity" : {
          "type" : "number"
        },
        "initialEstimateSymptomSpecificity" : {
          "type" : "number"
        },
        "maximumSocialContactReduction" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "name" : {
          "type" : "string"
        },
        "symptomSensitivity" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        },
        "symptomSpecificity" : {
          "$ref" : "#/definitions/ImmutableSimpleDistribution"
        }
      }
    },
    "executionReplications" : {
      "type" : "integer"
    },
    "facets" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "modifications" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "appUseProbability" : {
                  "$ref" : "#/definitions/ImmutableSimpleDistribution"
                },
                "asymptomaticFraction" : {
                  "type" : "number"
                },
                "availableTests" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/definitions/TestParameters"
                  }
                },
                "caseFatalityRate" : {
                  "type" : "number"
                },
                "caseHospitalisationRate" : {
                  "type" : "number"
                },
                "complianceProbability" : {
                  "$ref" : "#/definitions/ImmutableSimpleDistribution"
                },
                "contactDetectedProbability" : {
                  "type" : "number"
                },
                "contactProbability" : {
                  "$ref" : "#/definitions/ImmutableSimpleDistribution"
                },
                "defaultBehaviourModelName" : {
                  "type" : "string"
                },
                "defaultPolicyModelName" : {
                  "type" : "string"
                },
                "importationProbability" : {
                  "type" : "number"
                },
                "inHostConfiguration" : {
                  "anyOf" : [ {
                    "$ref" : "#/definitions/ImmutableStochasticModel"
                  }, {
                    "$ref" : "#/definitions/ImmutablePhenomenologicalModel"
                  } ]
                },
                "initialEstimateInfectionDuration" : {
                  "type" : "number"
                },
                "initialEstimateSymptomSensitivity" : {
                  "type" : "number"
                },
                "initialEstimateSymptomSpecificity" : {
                  "type" : "number"
                },
                "maximumSocialContactReduction" : {
                  "$ref" : "#/definitions/ImmutableSimpleDistribution"
                },
                "name" : {
                  "type" : "string"
                },
                "symptomSensitivity" : {
                  "$ref" : "#/definitions/ImmutableSimpleDistribution"
                },
                "symptomSpecificity" : {
                  "$ref" : "#/definitions/ImmutableSimpleDistribution"
                }
              }
            }
          },
          "name" : {
            "type" : "string"
          }
        }
      }
    },
    "setupConfig" : {
      "type" : "array",
      "items" : {
        "anyOf" : [ {
          "type" : "object",
          "properties" : {
            "modifications" : {
              "type" : "array",
              "items" : {
                "type" : "object",
                "properties" : {
                  "initialImports" : {
                    "type" : "integer"
                  },
                  "name" : {
                    "type" : "string"
                  },
                  "networkConnectedness" : {
                    "type" : "integer"
                  },
                  "networkRandomness" : {
                    "type" : "number"
                  },
                  "networkSize" : {
                    "type" : "integer"
                  }
                }
              }
            },
            "name" : {
              "type" : "string"
            }
          }
        }, {
          "type" : "object",
          "properties" : {
            "modifications" : {
              "type" : "array",
              "items" : {
                "type" : "object",
                "properties" : {
                  "ageDistribution" : {
                    "type" : "object",
                    "properties" : {
                      "cumulativeProbability" : {
                        "type" : "array",
                        "items" : {
                          "type" : "number"
                        }
                      },
                      "maximum" : {
                        "type" : "number"
                      },
                      "minimum" : {
                        "type" : "number"
                      },
                      "x" : {
                        "type" : "array",
                        "items" : {
                          "type" : "number"
                        }
                      }
                    }
                  },
                  "initialImports" : {
                    "type" : "integer"
                  },
                  "name" : {
                    "type" : "string"
                  },
                  "networkConnectedness" : {
                    "type" : "integer"
                  },
                  "networkRandomness" : {
                    "type" : "number"
                  },
                  "networkSize" : {
                    "type" : "integer"
                  },
                  "oddsAppUseFromAge" : {
                    "anyOf" : [ {
                      "$ref" : "#/definitions/ImmutableEmpiricalFunction"
                    }, {
                      "$ref" : "#/definitions/ImmutableFixedValueFunction"
                    } ]
                  },
                  "oddsComplianceFromAge" : {
                    "anyOf" : [ {
                      "$ref" : "#/definitions/ImmutableEmpiricalFunction"
                    }, {
                      "$ref" : "#/definitions/ImmutableFixedValueFunction"
                    } ]
                  },
                  "oddsContactFromAgeDifference" : {
                    "anyOf" : [ {
                      "$ref" : "#/definitions/ImmutableEmpiricalFunction"
                    }, {
                      "$ref" : "#/definitions/ImmutableFixedValueFunction"
                    } ]
                  },
                  "oddsMaximumSocialContactReductionFromAge" : {
                    "anyOf" : [ {
                      "$ref" : "#/definitions/ImmutableEmpiricalFunction"
                    }, {
                      "$ref" : "#/definitions/ImmutableFixedValueFunction"
                    } ]
                  },
                  "oddsMobilityFromAge" : {
                    "anyOf" : [ {
                      "$ref" : "#/definitions/ImmutableEmpiricalFunction"
                    }, {
                      "$ref" : "#/definitions/ImmutableFixedValueFunction"
                    } ]
                  },
                  "oddsSevereOutcomeFromAge" : {
                    "anyOf" : [ {
                      "$ref" : "#/definitions/ImmutableEmpiricalFunction"
                    }, {
                      "$ref" : "#/definitions/ImmutableFixedValueFunction"
                    } ]
                  },
                  "oddsTransmissionFromAge" : {
                    "anyOf" : [ {
                      "$ref" : "#/definitions/ImmutableEmpiricalFunction"
                    }, {
                      "$ref" : "#/definitions/ImmutableFixedValueFunction"
                    } ]
                  },
                  "scaleIncubationPeriodFromAge" : {
                    "anyOf" : [ {
                      "$ref" : "#/definitions/ImmutableEmpiricalFunction"
                    }, {
                      "$ref" : "#/definitions/ImmutableFixedValueFunction"
                    } ]
                  },
                  "scaleRecoveryPeriodFromAge" : {
                    "anyOf" : [ {
                      "$ref" : "#/definitions/ImmutableEmpiricalFunction"
                    }, {
                      "$ref" : "#/definitions/ImmutableFixedValueFunction"
                    } ]
                  }
                }
              }
            },
            "name" : {
              "type" : "string"
            }
          }
        } ]
      }
    },
    "setupReplications" : {
      "type" : "integer"
    }
  }
}

=== ai4ci/jpansim2/src/test/resources/test-R0.json
{
  "batchConfig" : {
    "urnBase" : "test-R0",
    "simulationDuration" : 200,
    "exporters" : [ "DEMOGRAPHICS", "SUMMARY", "INFECTIVITY_PROFILE", "INTERNAL_STATE" ]
  },
  "setupConfig" : [ {
    "@type" : "watts-strogatz",
    "name" : "setup",
    "modifications" : [ ],
    "default" : {
      "@type" : "watts-strogatz",
      "name" : "setup",
      "initialImports" : 5,
      "networkSize" : 10000,
      "networkRandomness" : 0.15,
      "networkConnectedness" : 100
    }
  } ],
  "setupReplications" : 1,
  "executionConfig" : {
    "name" : "execution",
    "contactProbability" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.1,
      "dispersion" : 0.1
    },
    "contactDetectedProbability" : 0.9,
    "complianceProbability" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.99,
      "dispersion" : 0.001
    },
    "appUseProbability" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.97,
      "dispersion" : 0.01
    },
    "inHostConfiguration" : {
      "symptomCutoff" : 0.5,
      "infectiousnessCutoff" : 0.2,
      "incubationPeriod" : {
        "type" : "LOG_NORM",
        "central" : 5.0,
        "dispersion" : 2.0
      },
      "approxPeakViralLoad" : {
        "type" : "UNIMODAL_BETA",
        "central" : 0.5,
        "dispersion" : 0.1
      },
      "incubationToPeakViralLoadDelay" : {
        "type" : "LOG_NORM",
        "central" : 2.0,
        "dispersion" : 1.0
      },
      "peakToRecoveryDelay" : {
        "type" : "LOG_NORM",
        "central" : 8.0,
        "dispersion" : 3.0
      },
      "approxPeakImmuneResponse" : {
        "type" : "UNIMODAL_BETA",
        "central" : 0.5,
        "dispersion" : 0.1
      },
      "peakImmuneResponseDelay" : {
        "type" : "LOG_NORM",
        "central" : 20.0,
        "dispersion" : 4.0
      },
      "immuneWaningHalfLife" : {
        "type" : "LOG_NORM",
        "central" : 300.0,
        "dispersion" : 10.0
      }
    },
    "availableTests" : [ {
      "testName" : "LFT",
      "sensitivity" : 0.9,
      "specificity" : 0.98,
      "meanTestDelay" : 0.0,
      "sdTestDelay" : 0.0
    }, {
      "testName" : "PCR",
      "sensitivity" : 0.8,
      "specificity" : 0.995,
      "meanTestDelay" : 3.0,
      "sdTestDelay" : 1.0
    } ],
    "symptomSensitivity" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.5,
      "dispersion" : 0.01
    },
    "symptomSpecificity" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.95,
      "dispersion" : 0.01
    },
    "initialEstimateInfectionDuration" : 10.0,
    "initialEstimateSymptomSensitivity" : 0.5,
    "initialEstimateSymptomSpecificity" : 0.95,
    "maximumSocialContactReduction" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.2,
      "dispersion" : 0.01
    },
    "defaultBehaviourModelName" : "Test",
    "defaultPolicyModelName" : "NoControl",
    "importationProbability" : 0.0,
    "rO" : 2.5
  },
  "facets" : [ {
    "name" : "R",
    "modifications" : [ {
      "name" : "1.0",
      "contactDetectedProbability" : 0.0,
      "rO" : 1.0
    }, {
      "name" : "2.0",
      "contactDetectedProbability" : 0.0,
      "rO" : 2.0
    }, {
      "name" : "3.0",
      "contactDetectedProbability" : 0.0,
      "rO" : 3.0
    } ]
  } ],
  "executionReplications" : 1
}

=== ai4ci/jpansim2/src/test/resources/age-stratification.json
{
  "batchConfig" : {
    "urnBase" : "age-stratification",
    "simulationDuration" : 200,
    "exporters" : [ "SUMMARY", "INTERNAL_STATE", "HISTORICAL_TESTS", "CONTACT_NETWORK", "INFECTIVITY_PROFILE", "DEMOGRAPHICS" ]
  },
  "setupConfig" : [ {
    "@type" : "age-stratified",
    "name" : "age-stratified",
    "modifications" : [ ],
    "default" : {
      "@type" : "age-stratified",
      "name" : "age-stratified",
      "initialImports" : 5,
      "networkSize" : 10000,
      "ageDistribution" : {
        "minimum" : 0.0,
        "maximum" : 120.0,
        "x" : [ 18.0, 45.0, 65.0, 85.0 ],
        "cumulativeProbability" : [ 0.1, 0.5, 0.75, 0.9 ]
      },
      "networkConnectedness" : 100,
      "networkRandomness" : 0.1,
      "oddsContactFromAgeDifference" : {
        "x" : [ 0.0, 10.0, 25.0, 40.0, 60.0, 70.0 ],
        "y" : [ 2.0, 0.5, 1.5, 0.5, 1.0, 0.5 ],
        "link" : "LOG"
      }
    }
  } ],
  "setupReplications" : 1,
  "executionConfig" : {
    "name" : "execution",
    "asymptomaticFraction" : 0.5,
    "caseHospitalisationRate" : 0.05,
    "caseFatalityRate" : 0.01,
    "contactProbability" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.5,
      "dispersion" : 0.25
    },
    "contactDetectedProbability" : 0.9,
    "complianceProbability" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.99,
      "dispersion" : 0.1
    },
    "appUseProbability" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.97,
      "dispersion" : 0.1
    },
    "inHostConfiguration" : {
      "@type" : "phenomenological",
      "infectiousnessCutoff" : 0.2,
      "incubationPeriod" : {
        "type" : "LOG_NORM",
        "central" : 5.0,
        "dispersion" : 2.0
      },
      "approxPeakViralLoad" : {
        "type" : "UNIMODAL_BETA",
        "central" : 0.5,
        "dispersion" : 0.1
      },
      "incubationToPeakViralLoadDelay" : {
        "type" : "LOG_NORM",
        "central" : 2.0,
        "dispersion" : 1.0
      },
      "peakToRecoveryDelay" : {
        "type" : "LOG_NORM",
        "central" : 8.0,
        "dispersion" : 3.0
      },
      "approxPeakImmuneResponse" : {
        "type" : "UNIMODAL_BETA",
        "central" : 0.5,
        "dispersion" : 0.1
      },
      "peakImmuneResponseDelay" : {
        "type" : "LOG_NORM",
        "central" : 20.0,
        "dispersion" : 4.0
      },
      "immuneWaningHalfLife" : {
        "type" : "LOG_NORM",
        "central" : 300.0,
        "dispersion" : 10.0
      }
    },
    "availableTests" : [ {
      "testName" : "LFT",
      "sensitivity" : 0.9,
      "specificity" : 0.98,
      "meanTestDelay" : 0.0,
      "sdTestDelay" : 0.0
    }, {
      "testName" : "PCR",
      "sensitivity" : 0.8,
      "specificity" : 0.995,
      "meanTestDelay" : 3.0,
      "sdTestDelay" : 1.0
    } ],
    "symptomSensitivity" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.5,
      "dispersion" : 0.1
    },
    "symptomSpecificity" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.95,
      "dispersion" : 0.1
    },
    "initialEstimateInfectionDuration" : 10.0,
    "initialEstimateSymptomSensitivity" : 0.5,
    "initialEstimateSymptomSpecificity" : 0.95,
    "maximumSocialContactReduction" : {
      "type" : "UNIMODAL_BETA",
      "central" : 0.2,
      "dispersion" : 0.1
    },
    "defaultBehaviourModelName" : "Test",
    "defaultPolicyModelName" : "NoControl",
    "importationProbability" : 0.0,
    "demographicAdjustment" : {
      "contactProbability" : {
        "x" : [ 0.0, 5.0, 15.0, 25.0, 45.0, 75.0 ],
        "y" : [ 2.0, 1.0, 1.5, 1.25, 0.8, 1.2 ],
        "link" : "LOG"
      },
      "complianceProbability" : {
        "value" : 1.0
      },
      "appUseProbability" : {
        "value" : 1.0
      },
      "maximumSocialContactReduction" : {
        "value" : 1.0
      },
      "peakToRecoveryDelay" : {
        "x" : [ 0.0, 5.0, 15.0, 25.0, 45.0, 65.0 ],
        "y" : [ 1.0, 0.5, 0.5, 0.75, 1.0, 2.0 ],
        "link" : "LOG"
      },
      "incubationPeriod" : {
        "value" : 1.0
      },
      "immuneWaningHalfLife" : {
        "x" : [ 0.0, 5.0, 15.0, 25.0, 45.0, 65.0, 85.0 ],
        "y" : [ 1.0, 2.0, 2.0, 1.5, 1.0, 0.5, 0.25 ],
        "link" : "LOG"
      }
    },
    "rO" : 2.5
  },
  "facets" : [ ],
  "executionReplications" : 1
}
